on:

  push:
  
  schedule:
    - cron: "*/5 * * * *"

name: CI

jobs:

  unittest:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Run test
      run:
        make test

    - name: Run integration test
      run:
        make shell-test

  linter:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Lint check
      run:
        make lint

  docker:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Docker check
      run: |
        docker build -t blc .
        docker run blc --help


